# Generated by Django 4.2.11 on 2024-04-09 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 16, 14, 21, 864403, tzinfo=datetime.timezone.utc)),
        ),
    ]
